version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    groups:
      official-actions:
        patterns:
          - actions/*
          - github/codeql-action

  - package-ecosystem: npm
    directory: /quality/tools/js
    schedule:
      interval: weekly
    labels:
      - dependencies
      - quality-toolchain
    versioning-strategy: increase

  - package-ecosystem: pip
    directory: /quality/tools/python
    schedule:
      interval: weekly
    labels:
      - dependencies
      - quality-toolchain
    versioning-strategy: increase
